[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
via-ir = true
verbosity = 2
ffi = true
remappings = [
    "@openzeppelin-contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@openzeppelin-contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "forge-std/=dependencies/forge-std-1.9.4/src",
]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_TOKEN}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_TOKEN}"
polygon_pos = "https://polygon-mainnet.infura.io/v3/${INFURA_TOKEN}"
polygon_zkevm = "https://zkevm-rpc.com"
polygon_zkevm_testnet = "https://rpc.public.zkevm-test.net"

[dependencies]
forge-std = { version = "1.9.4" }
"@openzeppelin-contracts" = { version = "5.1.0" }
"@openzeppelin-contracts-upgradeable" = { version = "5.1.0" }

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_TOKEN}"

[soldeer]
remappings_generate = true
remappings_version = false
remappings_location = "config"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options